# Generated by Django 5.0 on 2025-01-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('project_number', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('down_payment_date', models.DateField(blank=True, null=True)),
                ('structure_type', models.CharField(max_length=50)),
                ('erection_subcontractor', models.CharField(max_length=100)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment_ack', models.BooleanField(default=False)),
                ('payment_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_2_ack', models.BooleanField(default=False)),
                ('payment_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_3_ack', models.BooleanField(default=False)),
                ('payment_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_4_ack', models.BooleanField(default=False)),
                ('payment_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_5_ack', models.BooleanField(default=False)),
                ('preliminary_retention', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ho_retention', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('incoterm', models.CharField(max_length=20)),
                ('scope_of_work', models.TextField()),
                ('project_nature', models.CharField(max_length=20)),
                ('contractual_tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engineering_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('galvanized', models.BooleanField(default=False)),
                ('galvanization_microns', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m2_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paint_coat_1', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_1_microns', models.IntegerField(blank=True, null=True)),
                ('coat_1_liters_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paint_coat_2', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_2_microns', models.IntegerField(blank=True, null=True)),
                ('coat_2_liters_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paint_coat_3', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_3_microns', models.IntegerField(blank=True, null=True)),
                ('coat_3_liters_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paint_coat_4', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_4_microns', models.IntegerField(blank=True, null=True)),
                ('coat_4_liters_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('top_coat_ral_number', models.CharField(blank=True, max_length=20, null=True)),
                ('welding_process', models.CharField(max_length=20)),
                ('welding_wire_aws_class', models.CharField(max_length=50)),
                ('pqr_no', models.CharField(max_length=50)),
                ('wps_no', models.CharField(max_length=50)),
                ('standard_code', models.CharField(max_length=50)),
                ('erectable', models.BooleanField(blank=True, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('down_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_structures', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hexa_projects',
            },
        ),
    ]
