# Generated by Django 5.0 on 2025-01-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('designer_name', models.CharField(max_length=100)),
                ('subcontractor_name', models.CharField(max_length=100)),
                ('design_start_date', models.DateField(blank=True, null=True)),
                ('design_end_date', models.DateField(blank=True, null=True)),
                ('shop_drawing_start_date', models.DateField(blank=True, null=True)),
                ('shop_drawing_end_date', models.DateField(blank=True, null=True)),
                ('production_start_date', models.DateField(blank=True, null=True)),
                ('production_end_date', models.DateField(blank=True, null=True)),
                ('erection_applicable', models.BooleanField(default=True)),
                ('erection_start_date', models.DateField(blank=True, null=True)),
                ('erection_end_date', models.DateField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('qc_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='projects.project')),
            ],
            options={
                'db_table': 'hexa_buildings',
                'ordering': ['building_name'],
            },
        ),
    ]
