# Generated by Django 5.0 on 2025-01-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_building'),
    ]

    operations = [
    ]
