# Generated by Django 5.0 on 2025-01-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20250112_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('part_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('assembly_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_assembly_mark', models.CharField(max_length=100)),
                ('part_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_area_single', models.CharField(blank=True, max_length=255, null=True)),
                ('net_area_all', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_part_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight_total', models.CharField(blank=True, max_length=255, null=True)),
                ('revision', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='projects.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='projects.project')),
            ],
            options={
                'db_table': 'HEXA_rawdata',
            },
        ),
    ]
