# Generated by Django 5.0 on 2025-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='log_designation',
            field=models.CharField(default='PENDING', help_text='Unique identifier for production, QC, logistics, and erection activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='single_part_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sub_assembly_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together={('project', 'building', 'log_designation')},
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['log_designation'], name='HEXA_rawdat_log_des_9ef5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['project', 'building', 'log_designation'], name='HEXA_rawdat_project_e7acd6_idx'),
        ),
    ]
