# Generated by Django 5.0 on 2025-01-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_rawdata_log_designation_alter_rawdata_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together=set(),
        ),
    ]
