# Generated by Django 5.0 on 2025-01-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_consolidated_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
