# Generated by Django 5.0 on 2025-01-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_team_facility_delete_facility_delete_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionLog',
        ),
    ]
