# Generated by Django 5.0 on 2025-01-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_designation', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('process', models.CharField(choices=[('fit-up', 'Fit-up'), ('welding', 'Welding'), ('visualization', 'Visualization')], max_length=50)),
                ('production_date', models.DateField()),
                ('facility', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prod_productionlog',
            },
        ),
    ]
